### ISSUE TITLE
ScanData Stream API v1

### ISSUE THREAD

**Issue by gregwinn** [bluzone/consumer-service#1]
Hello,
     I am trying to use your ScanData Stream API v1 and having some issues. I am unable to locate the correct URI to request data for this service using this documentation: (https://bluvision.atlassian.net/wiki/display/PDP/ScanData+Stream+API+v1).

Also I would like to know if the data is combined into one stream once you are using more BluFi's or if you have to open a separate stream via ID for each BluFi to look at the data?

Thank you in advance for your help.

**Comment by robert-dare** [comment]
Hi Greg,

The URL is the base URL that you use to access the Bluzone portal.  We were unspecific in the documentation because some users are on beta, dev, uat portals.  

The stream is an aggregation of all Blufis.  There is a separate URL that can access an individual stream.  You can find that URL in the Bluzone portal under the Blufi details "Activity" tab.

Regards,

Robert
